name: PlatformIO CI

on: [push]

jobs:
  build-calibration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build Calibration
        run: |
          cd calibration
          pio run

  build-firmware:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Install PIO in Home
        run: |
          python3 -c "$(curl -fsSL https://raw.githubusercontent.com/platformio/platformio/master/scripts/get-platformio.py)"
          echo "PATH=\"\$PATH:\$HOME/.platformio/penv/bin\"" >> $HOME/.bashrc
          source $HOME/.bashrc

      - name: Install required pip packages
        run: |
          source $HOME/.platformio/penv/bin/activate
          pip install --upgrade catkin_pkg
          pip uninstall em
          pip install empy lark
      
      - name: Build Firmware
        env:
            ROS_DISTRO: humble
        run: |
          cd firmware
          pio run
