name: ROS Galactic Firmware Build

on:
  # run on PRs and pushes to galactic branch(es)
  pull_request:
    branches:
      - galactic*
    paths-ignore:
      - 'docs/**'
      - .gitignore
      - LICENSE
      - README.md

  push:
    branches:
      - galactic*
    paths-ignore:
      - 'docs/**'
      - .gitignore
      - LICENSE
      - README.md
  
  # Run daily at midnight to detect flakiness and broken dependencies
  schedule:
    - cron: '0 0 * * *'

  # Allow manual triggering
  workflow_dispatch:


jobs:
  firmware:
    uses: ./.github/workflows/reusable-platformio-ci.yml
    with:
      ros_distro: galactic
      reference: galactic
