name: ROS Humble Firmware Build

on:
  pull_request:
    branches:
      - humble*
  push:
    branches:
      - humble*
  schedule:
    # Run every morning to detect flakiness and broken dependencies
    - cron: '03 1 * * *'
  workflow_dispatch:


jobs:
  firmware:
    uses: ./.github/workflows/reusable-platformio-ci.yml
    with:
      ros_distro: humble
