name: ROS Rolling Firmware Build

# TODO rename main branch of repo to rolling and then fix
on:
  pull_request:
    branches:
      - galactic
  push:
    branches:
      - galactic
  schedule:
    # Run every morning to detect flakiness and broken dependencies
    - cron: '03 1 * * *'


jobs:
  firmware:
    uses: ./.github/workflows/reusable-platformio-ci.yml
    with:
      ros_distro: rolling
      reference: galactic
