name: ROS Rolling Firmware Build

env:
  DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}

on:
  pull_request:
    # Run on PRs to only the default branch (usually main or master)
    branches:
      - DEFAULT_BRANCH
    # Don't run when the following files are changed which don't effect firmware.
    paths-ignore:
      - 'docs/**'
      - .gitignore
      - LICENSE
      - README.md
  
  # not specifying branches means will run on pushes to any branches. This is alright for rolling
  push:
    # Run on pushes to any branches except these distro-specific branches
    branches-ignore:
      - iron*
      - humble*
      - galactic*
      - foxy*
    # Don't run when the following files are changed which don't effect firmware.
    paths-ignore:
      - 'docs/**'
      - .gitignore
      - LICENSE
      - README.md
    
  # Run daily at midnight to detect flakiness and broken dependencies
  schedule:
    - cron: '0 0 * * *'

  # Allow manual triggering
  workflow_dispatch:


jobs:
  firmware:
    uses: ./.github/workflows/reusable-platformio-ci.yml
    with:
      ros_distro: rolling
      # The reference field will be set to the default branch only if the event that triggered the workflow is schedule. Otherwise, it will be left blank.
      reference: ${{ github.event_name == 'schedule' && github.event.repository.default_branch || '' }}
