name: ROS Rolling Firmware Build

env:
  DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}

on:
  # avoid running on distro branches but otherwise always
  pull_request:
    branches:
      - DEFAULT_BRANCH
    paths-ignore:
      - 'docs/**'
      - .gitignore
      - LICENSE
      - README.md
  
  # not specifying branches means will run on pushes to any branches. This is alright for rolling
  push:
    paths-ignore:
      - 'docs/**'
      - .gitignore
      - LICENSE
      - README.md
    
  # Run daily at midnight to detect flakiness and broken dependencies
  schedule:
    - cron: '0 0 * * *'

  # Allow manual triggering
  workflow_dispatch:


jobs:
  firmware:
    uses: ./.github/workflows/reusable-platformio-ci.yml
    with:
      ros_distro: rolling
